# Generated by Django 4.2.4 on 2024-03-19 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasaulApp', '0002_alter_estudiante_options_entregable_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregable',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='entregable',
            name='estudiante_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BasaulApp.estudiante'),
        ),
    ]
